### ISSUE TITLE
Creating tutorial about nested proofs

### ISSUE THREAD

**Issue by alvaro-alonso** [ZoKratesPlus/tutorials#1]
Zokrates support the composition of proofs. Meaning, you can write a proof that verifies the validity of another proof.
This can have a huge impact in scalabity by breaking down bigger proofs into smaller units, which the aggregated correctnes can be assed in a single proof. 

The goal of this issue is to create a tutorial, as a first step to get acquainted with the topic 

**Resources**
- source code: https://github.com/Zokrates/ZoKrates/blob/0.8.3/zokrates_stdlib/stdlib/snark/gm17.zok
- test: https://github.com/Zokrates/ZoKrates/blob/0.8.3/zokrates_stdlib/tests/tests/snark/gm17.zok

**Comment by alvaro-alonso** [comment]
Advantages:
  ➕ Can lead to less Transactions on the Blockchain
  ➕ Break-down of very big proofs
  ➕ can speedup things if underlying proofs computed in parallel (to proof)
Disadvantages:
  ➖ Memory overhead (400 MB x number of proofs)
  ➖ CPU overhead

**Comment by alvaro-alonso** [comment]
Atm it seems that recursive proofs do work when the "parent" and "child" proofs are compiled under the `bw6_761`, `bls12_377` curves respectively.

**Comment by alvaro-alonso** [comment]
The source code and support material is awaiting review on https://github.com/ZoKratesPlus/tutorials/pull/2

The blog post is WIP on https://github.com/ZoKratesPlus/zokratesplus.github.io/pull/4

**Comment by alvaro-alonso** [comment]
@chGoodchild please review the linked PR, for necessary changes. Once approved it will be squashed and merged to main

**Comment by chGoodchild** [comment]
@alvaro-alonso , I added some silly questions I had following the tutorial. Perhaps it's worth addressing some of those so that your audience gets a good feeling about what happened in the tutorial.
